sudo: false
dist: trusty
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
env:
 - BRBASE=3.16 BRPVD=master BRPVA=devel
 - BRBASE=3.16 BRPVD=master BRPVA=devel CMPLR=clang
 - BRBASE=3.16 BRPVD=master BRPVA=devel USR_CXXFLAGS=-std=c++11
 - BRBASE=3.16 BRPVD=master BRPVA=devel USR_CXXFLAGS=-std=c++11 CMPLR=clang
 - BRBASE=3.15 BRPVD=master BRPVA=devel
install:
 - ./build-deps.sh
script:
 - make -j2
 - make tapfiles
 - find . -name '*.tap' -print0 | xargs -0 -n1 prove -e cat -f
